# BusinessException messages
businessException.InternalError.message=The server encountered an internal error or misconfiguration and was unable to complete your request.
businessException.note.element.NotFound.message=note element with id {0} could not be found.
businessException.note.element.AlreadyExists.message=note element with id {0} already exists.
businessException.note.module.NotFound.message=note module with id {0} could not be found.
businessException.note.module.AlreadyExists.message=note module with id {0} already exists.
businessException.module.NotFound.message=module with id {0} could not be found.
businessException.element.NotFound.message=element with id {0} could not be found.

